













/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module App.CodeCamper {
    /** Generated from CodeCamper.Da.Attendance **/
    export interface IModelAttendance {
        PersonId: number;
        Person: App.CodeCamper.IModelPerson;
        SessionId: number;
        Session: App.CodeCamper.IModelSession;
        Rating: number;
        Text: string;
    }
    /** Generated from CodeCamper.Da.Person **/
    export interface IModelPerson {
        Id: number;
        FirstName: string;
        LastName: string;
        Email: string;
        Blog: string;
        Twitter: string;
        Gender: string;
        ImageSource: string;
        Bio: string;
        SpeakerSessions: App.CodeCamper.IModelSession[];
        AttendanceList: App.CodeCamper.IModelAttendance[];
        FullName: string;
    }
    /** Generated from CodeCamper.Da.Room **/
    export interface IModelRoom {
        Id: number;
        Name: string;
    }
    /** Generated from CodeCamper.Da.Session **/
    export interface IModelSession {
        Id: number;
        Title: string;
        Code: string;
        SpeakerId: number;
        TrackId: number;
        TimeSlotId: number;
        RoomId: number;
        Level: string;
        Tags: string;
        Description: string;
        Speaker: App.CodeCamper.IModelPerson;
        Track: App.CodeCamper.IModelTrack;
        TimeSlot: App.CodeCamper.IModelTimeSlot;
        Room: App.CodeCamper.IModelRoom;
        AttendanceList: App.CodeCamper.IModelAttendance[];
    }
    /** Generated from CodeCamper.Da.TimeSlot **/
    export interface IModelTimeSlot {
        Id: number;
        Start: string;
        IsSessionSlot: boolean;
        Duration: number;
    }
    /** Generated from CodeCamper.Da.Track **/
    export interface IModelTrack {
        Id: number;
        Name: string;
    }
}
